version: '3'

services:
  db:
    image: postgres
    container_name: students_db
    ports:
      - 5555:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_students
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env
    depends_on:
      - db
  
  react_app:
    container_name: react_students
    build: ./front-end
    env_file:
      - front-end/.env
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_students
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - react_app

volumes:
  postgres:
  build_react:
